// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn-info': string;
  'button': string;
  'buttonSuccess': string;
  'primary': string;
}
declare var cssExports: CssExports;
export = cssExports;
