// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'App-logo': string;
  'app-button': string;
  'app-title': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
